version: '3.8'

services:
  backend:
    build: ./backend
    container_name: ebarangay-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - npm_default
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: ebarangay-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - npm_default
    depends_on:
      - backend

networks:
  npm_default:
    external: true
